### ISSUE TITLE
404s for bootstrap.css, topojson.js, and bootstrap.js

### ISSUE THREAD

**Issue by bfreeds** [bowmanmc/squatchin#1]
Hi Michael,

I've been playing around with this after js.geo to learn how to use phantomjs with d3, and I noticed when I run `gulp` I get 404s for:  
- bower_components/bootstrap/dist/css/bootstrap.css  
- bower_components/bootstrap/dist/js/bootstrap.js  
- bower_components/topojson/topojson.js.  

I'll keep looking as I mess around, but I was thinking it has something to do with the `makedist` gulp task (for the bootstrap libraries) and for topojson, does it just need to be added to the bower.json file?

Thanks for putting this together and presenting at js.geo, and sorry if this is a naive question-i'm pretty new to node.

Brandyn

**Comment by bowmanmc** [comment]
No problem. I should document the process better. You just need to run "bower install". If you don't have bower yet, run "npm install -g bower" first.

**Comment by bfreeds** [comment]
Hmm, I had already run bower install.  I added topojson to the bower.json before running `$bower install`, which cleared that 404.  

For the boostrap.css & bootstrap.js, though, I don't have any bootstrap/dist directory.  There is a "bower_components/bootstrap-sass/assets/javascripts/bootstrap.js".  I think for the the css is in .scss, though.  Is a function in the gulpfile suppossed to compile bootstrap-sass to css in the bower_components/bootstrap/dist directory?

(It probably doesn't matter, but I just wanted to ask to see if I was missing something when reading the code).  I'd be happy to help out with some of the documentation as I figure out how this works.

**Comment by bowmanmc** [comment]
Ah ok. Yeah, those weren't being used. I had switched to the sass version of bootstrap and didn't remove the old one from index.html. I took them out. Thanks!

**Comment by bfreeds** [comment]
Gotchya, thanks for following up.  Love this project and your presentation a couple weeks ago!

**Comment by bowmanmc** [comment]
Thanks a lot Brandyn! Good luck and let me know if you have any more questions.
